### PR TITLE
Fix #2685 [BUG] S3 block spilling no longer passes request headers

### LINKED ISSUE #2685: [BUG] S3 block spilling no longer passes request headers
**Describe the bug**

Connectors that make use of S3BlockSpiller can be configured with:

- `spill_put_request_headers`: A JSON encoded map of request headers and values for the Amazon S3 putObject request

In older connector versions i.e `v2023.30.1`, these were then set as request headers on the PutObject request. Now they are set as object metadata.

Believe would impact any connectors that makes use of spilling, but encountered specifically on mysql, postgres and MSK.

Appears to be related to [this change to S3BlockSpiller.java](https://github.com/awslabs/aws-athena-query-federation/commit/8fe875f262cb343132a8556c7985e9068de44de1#diff-8ba037f347245054450d3c3da288f94d97bff0c2150363ee722c3919dd4234f7), where `SPILL_PUT_REQUEST_HEADERS_ENV` used to be added as request headers (via `request.putCustomRequestHeader`), but are now added to object metadata (via `.metadata(getRequestHeadersFromEnv())`)

**To Reproduce**
Steps to reproduce the behaviour:
1. S3 bucket setup for spill w/ KMS key for SSE-KMS
2. nysql/postgres instance and seed with data where a select can exceed block chunk size 
3. Lambda connectors @ v2025.10.1  (any version after v2024.42.1)
   - `spill_bucket=<spill bucket>`
   - `spill_prefix=mysql-spill`
   - `test_connection_string=mysql://jdbc:mysql://test.....eu-west-2.rds.amazonaws.com:3306/information_schema?secret=${/secret/path}`
   - `spill_put_request_headers={"x-amz-server-side-encryption":"aws:kms","x-amz-server-side-encryption-aws-kms-key-id":"arn:aws:kms:eu-west-2:xxxxxxxxxxxx:key/<key id>"}` 
4. Query in Athena that causes spill, request headers not set on PutObject request
5. Intended request headers are actually set in object metadata
6. Request headers missing in Cloudtrail (after enabling S3 data events)

**Expected behaviour**

`spill_put_request_headers` map passed and set as request headers, if metadata is intended to be set on spill objects then this could be passed with dedicated config for this (i.e `spill_object_metadata`)

**Screenshots / Exceptions / Errors**

Image

Cloudtrail event missing request headers:
```
  "requestParameters": {
    "bucketName": "<spill bucket>",
    "Host": "<spill bucket>.s3.eu-west-2.amazonaws.com",
    "key": "mysql-spill/61ecb3e3-33d7-495b-9015-f07f15490280/b43cfe8b-d88d-487a-b9e7-d26e9c41078b.0"
  },
  "responseElements": {
    "x-amz-server-side-encryption": "aws:kms",
    "x-amz-server-side-encryption-aws-kms-key-id": "arn:aws:kms:eu-west-2:xxxxxxxxxxxxx:key/<key id>"
  },
  "additionalEventData": {
    "SignatureVersion": "SigV4",
    "CipherSuite": "TLS_AES_128_GCM_SHA256",
    "bytesTransferredIn": 3867866,
    "SSEApplied": "Default_SSE_KMS",
    "AuthenticationMethod": "AuthHeader",
    "x-amz-id-2": "...",
    "bytesTransferredOut": 0
  }
```

Cloudtrail event of prior version of connectors / connectors built locally with request headers re-instated
```
  "requestParameters": {
    "bucketName": "<spill bucket>",
    "x-amz-server-side-encryption-aws-kms-key-id": "arn:aws:kms:eu-west-2:xxxxxxxxxxxx:key/<key id>",
    "Host": "<spill bucket>.s3.eu-west-2.amazonaws.com",
    "x-amz-server-side-encryption": "aws:kms",
    "key": "mysql-spill/2f1303d2-033b-45c2-9dc7-3ca679b2d2d5/590ff0e7-e8a9-4219-aa04-34ca389e73c1.0"
  },
  "responseElements": {
    "x-amz-server-side-encryption": "aws:kms",
    "x-amz-server-side-encryption-aws-kms-key-id": "arn:aws:kms:eu-west-2:xxxxxxxxxxxx:key/<key id>"
  },
  "additionalEventData": {
    "SignatureVersion": "SigV4",
    "CipherSuite": "TLS_AES_128_GCM_SHA256",
    "bytesTransferredIn": 3867866,
    "SSEApplied": "SSE_KMS",
    "AuthenticationMethod": "AuthHeader",
    "x-amz-id-2": "...",
    "bytesTransferredOut": 0
  },
```

**Connector Details (please complete the following information):**
 - Version: > v2024.42.1
 - Name: federation-sdk
 - Athena Query IDs [if applicable] -

**Additional context**

### PR DESCRIPTION
**Pull request by Trianz-Akshay**
*Issue #, if available:*
[#2685](https://github.com/awslabs/aws-athena-query-federation/issues/2685)

*Description of changes:*

This PR fixes issue #2685 where `spill_put_request_headers` configuration was incorrectly being set as object metadata instead of request headers on S3 PutObject requests. This caused SSE-KMS encryption headers to not appear in CloudTrail `requestParameters`, breaking encryption requirements and audit logging.

## Problem

In versions >= v2024.42.1, the `spill_put_request_headers` environment variable values were being set as object metadata using `.metadata()` instead of request headers. This meant:

- **SSE-KMS headers** (`x-amz-server-side-encryption`, `x-amz-server-side-encryption-aws-kms-key-id`) were not sent as request parameters
- **CloudTrail logs** showed headers missing from `requestParameters` (they only appeared in `responseElements`)

## Solution

Changed `S3BlockSpiller.write()` to use `AwsRequestOverrideConfiguration` to set headers as request headers via `.overrideConfiguration()` instead of `.metadata()`.

Test Document:
[Bug_Fix_2685.docx](https://github.com/user-attachments/files/23358276/Bug_Fix_2685.docx)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java [hunk 1]
```diff
@@ -343,6 +344,23 @@ private Map<String, String> getRequestHeadersFromEnv()
         return Collections.emptyMap();
     }
 
+    /**
+     * Creates an AwsRequestOverrideConfiguration with custom headers from the environment
+     */
+    private AwsRequestOverrideConfiguration createRequestOverrideConfig()
```
Comment (AbdulR3hman) [inline athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java]: return an optional here is better than nulls.

Comment (Trianz-Akshay) [reply athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/data/S3BlockSpiller.java]: Thanks for the suggestion. Updated the code to return an Optional instead of null.

**Review by chngpe — APPROVED** [review]
